APP_NAME: "digisatlink"
HTTP_PORT: "8080"
APP_URL: "http://localhost:8080"

DB_DRIVER: "postgres"
DB_URL: "postgres://postgres:root@localhost:5432/finals_db?sslmode=disable"
DB_MAX_IDLE_CONNECTIONS: "20"
DB_MAX_OPEN_CONNECTIONS: "50"
DB_MAX_IDLE_DURATION_IN_SECS: "60"
DB_MAX_LIFE_TIME_DURATION_IN_SECS: "300"
DB_MIGRATION_PATH: "file://migrations"

JWT_SECRET_KEY: "JWTKEY123"
JWT_LOGIN_EXPIRATION_DURATION_HOUR: "24"
JWT_REFRESH_EXPIRATION_DURATION_DAYS: "7"

FIREBASE_TYPE: ""
FIREBASE_PROJECT_ID: ""
FIREBASE_PRIVATE_KEY_ID: ""
FIREBASE_PRIVATE_KEY: ""
FIREBASE_CLIENT_EMAIL: ""
FIREBASE_CLIENT_ID: ""
FIREBASE_AUTH_URI: ""
FIREBASE_TOKEN_URI: ""
FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ""
FIREBASE_CLIENT_X509_CERT_URL: ""
FIREBASE_UNIVERSE_DOMAIN: ""

AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
AWS_REGION: ""
AWS_BUCKET_NAME: ""
AWS_BASE_URL: "https://s3.amazonaws.com/"
